my_project/admin_side/urls.py
from django.urls import path
from admin_side import views


urlpatterns = [
    path('admin_login', views.admin_login , name ='admin_login'),
    path('admin_logout/',views.admin_logout,name='admin_logout'),
    path('admin_index/',views.admin_index,name='admin_index'),
    path('admin_service/',views.admin_service,name='admin_service'),   
    path('admin_service_add/',views.admin_service_add,name='admin_service_add'),
    path('admin_service_edit/<int:id>',views.admin_service_edit,name='admin_service_edit'),
    path('admin_service_delete/<int:id>',views.admin_service_delete,name='admin_service_delete'),  
    path('customers/',views.customers,name='customers'),
    path('block_user/<int:user_id>/', views.block_user, name='block_user'),
    path('admin_category/',views.admin_category,name='admin_category'),
    path('admin_category_insert/',views.admin_category_insert,name='admin_category_insert'),
    path('admin_type/',views.admin_type,name='admin_type'), 
    path('admin_type_insert/',views.admin_type_insert,name='admin_type_insert'),
    path('admin_type_edit/<int:id>',views.admin_type_edit,name='admin_type_edit'),
    path('type_available/<int:type_id>/',views.type_available,name='type_available'),
    path('admin_category_edit/<int:id>',views.admin_category_edit,name='admin_category_edit'),
    path('admin_delete_category/<int:id>/', views.admin_delete_category, name='admin_delete_category'),
    path('block_unblock_category/<int:id>/', views.block_unblock_category, name='block_unblock_category'),
    path('admin_varient/',views.admin_varient,name='admin_varient'),  
    path('admin_varient_add/',views.admin_varient_add,name='admin_varient_add'), 
    path('admin_varient_edit/<int:id>',views.admin_varient_edit,name='admin_varient_edit'), 
    path('admin_varient_delete/<int:id>',views.admin_varient_delete,name='admin_varient_delete'), 
    path('admin_provider_type/',views.admin_provider_type,name='admin_provider_type'), 
    path('admin_provider_type_insert/',views.admin_provider_type_insert,name='admin_provider_type_insert'),
    path('admin_provider_type_edit/<int:id>',views.admin_provider_type_edit,name='admin_provider_type_edit'),
    path('order/',views.order,name='order'),
    path('orderitems/<int:order_number>',views.orderitems,name='orderitems'),
    path('sales_report',views.sales_report,name='sales_report'),
    path('service-offers/',views.service_offers, name='service-offers'),
    path('create-service-offer/',views.create_service_offer, name='create-service-offer'),
    path('edit-service-offers/<int:id>',views.edit_service_offers, name='edit-service-offers'),
    path('delete-service-offer/<int:id>/',views.delete_service_offer, name='delete-service-offer'),
    path('category-offers/',views.category_offers, name='category-offers'),
    path('create-category-offer/',views.create_category_offer, name='create-category-offer'),
    path('edit-category-offers/<int:id>',views.edit_category_offers, name='edit-category-offers'), 
    path('delete-category-offer/<int:id>/',views.delete_category_offer, name='delete-category-offer'),
    path('admin_coupon/',views.admin_coupon,name='admin_coupon'),
    path('create_coupon/',views.create_coupon, name='create_coupon'),
    path('edit_coupon/<int:id>',views.edit_coupon,name='edit_coupon'),
    path('delete_coupon/<int:id>',views.delete_coupon,name='delete_coupon'),
    path('admin_banner/',views.admin_banner,name='admin_banner'),
    path('create_banner/',views.create_banner, name='create_banner'),
    path('update_banner/<int:id>',views.update_banner,name='update_banner'),
    path('delete_banner/<int:id>',views.delete_banner,name='delete_banner'),























]

my_project/my_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("user_side.urls")),
    path("", include("admin_side.urls")),
    path('payment/',include('payment.urls')),
    
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

my_project/payment/urls.py
from django.urls import path
from .import views

urlpatterns = [
    path('',views.checkout,name='checkout'),
    path('payment/',views.payment,name="payment"),
    path('paymenthandler/', views.paymenthandler, name='paymenthandler'),
    path('online_place_order', views.online_place_order, name='online_place_order'),
    path('place_order/',views.place_order,name="place_order"),
    path('order_success/', views.order_success, name='order_success'),
    path('wallet_place_order', views.wallet_place_order, name='wallet_place_order'),
    path('invoice/<int:order_id>/',views.invoice,name='invoice'),


]

my_project/admin_side/models.py
from django.db import models
from decimal import Decimal
from user_side.models import *

# Create your models here.


class ServiceOffer(models.Model):
    discount_percentage = models.DecimalField(max_digits=5, decimal_places=2, default=0.00)
    start_date = models.DateTimeField(null=True, blank=True)
    end_date = models.DateTimeField(null=True, blank=True)
    active = models.BooleanField(default=False)
    
    def __str__(self):
        return f"{self.discount_percentage}% Discount"

    def save(self, *args, **kwargs):
        if not isinstance(self.discount_percentage, Decimal):
            self.discount_percentage = Decimal(str(self.discount_percentage))
        super().save(*args, **kwargs)
    
class CategoryOffer(models.Model):
    category=models.ForeignKey(category,on_delete=models.SET_NULL, null=True)
    discount_percentage = models.DecimalField(max_digits=5, decimal_places=2, default=0.00)
    start_date = models.DateTimeField(null=True, blank=True)
    end_date = models.DateTimeField(null=True, blank=True)
    active = models.BooleanField(default=False)
    
    def __str__(self):
        return f"{self.discount_percentage}% Discount"

    def save(self, *args, **kwargs):
        if not isinstance(self.discount_percentage, Decimal):
            self.discount_percentage = Decimal(str(self.discount_percentage))
        super().save(*args, **kwargs)


class Coupon(models.Model):
    code = models.CharField(max_length=50,unique=True)
    discount = models.PositiveBigIntegerField(help_text='discount in percentage')
    active = models.BooleanField(default=True)
    active_date = models.DateField()
    expiry_date = models.DateField()
    created_date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.code
    

class Banner(models.Model):
    title = models.CharField(max_length=100)
    image = models.ImageField(upload_to='banners/')
    description1 = models.TextField(blank=True, null=True)
    description2 = models.TextField(blank=True, null=True)
    description3 = models.TextField(blank=True, null=True)
    start_date = models.DateField()
    end_date = models.DateField()
    is_active =models.BooleanField(default=True)

    def __str__(self):
        return self.title
    
    def update_status(self):
        today = timezone.now().date()
        return self.start_date <= today <=self.end_date

my_project/admin_side/views.py
from django.shortcuts import render,redirect
from django.contrib import messages,auth
from django.contrib.auth import authenticate, login,logout
from user_side.models import *
from django.contrib.auth.decorators import login_required
from django.shortcuts import get_object_or_404
from user_side.forms import *
from django.db import IntegrityError
from django.db import transaction
from django.http import HttpResponse, HttpResponseRedirect
from django.db.models.functions import TruncDate,TruncMonth, TruncYear
from django.db.models import Count
from django.forms.models import inlineformset_factory
from django.utils.timezone import make_aware
from django.views.decorators.cache import cache_control, never_cache
from datetime import datetime, timedelta
from payment.models import *
from .models import *
from .forms import *


# Create your views here.

def admin_login(request):
    if request.method == 'POST':
        email = request.POST['email']
        password = request.POST['password']
        user=authenticate(request, email=email,password=password)
        if user is not None and user.is_active and user.is_superadmin and user.is_staff and user.is_admin :
            login(request, user)
            messages.success(request, 'Successfully logged in.')
            return redirect('admin_index')
        else:
            messages.error(request, 'Invalid credentials')
            return render(request, 'admin_side/admin_login.html')
    return render(request, 'admin_side/admin_login.html')


def admin_logout(request):
    logout(request)
    messages.success(request, 'Successfully logged out.')
    return redirect(admin_login)


@never_cache
@login_required(login_url='admin_login')
@cache_control(no_cache=True, must_revalidate=True, no_store=True)
def admin_index(request):
    if not request.user.is_superadmin:
        return redirect('admin_login')
 
    service_count=Service.objects.count()
    category_count=category.objects.count()
    orders=CartOrder.objects.all()
    last_orders= CartOrder.objects.order_by('-created_at')[:5]
    orders_count=orders.count()
    total_users_count = CustomUser.objects.count()
    total = 0
    for order in orders:
        if order.status == 'Delivered':
            total += order.order_total
            
        if (order.payment and order.payment.payment_method == 'Razorpay' and order.status != 'Cancelled' ) or (order.payment and order.payment.payment_method == 'Wallet' and order.status != 'Cancelled'):
            total += order.order_total
    revenue=int(total)
    end_date = timezone.now()
    start_date = end_date - timedelta(days=7)
    print('Start Date:', start_date)
    print('End Date:', end_date)

    daily_order_counts = (
            CartOrder.objects
            .filter(created_at__range=(start_date, end_date))
            .values('created_at')
            .annotate(order_count=Count('id'))
            .order_by('created_at')
        )
    print(f'daily orrderr {daily_order_counts}')
    print('SQL Query:', daily_order_counts.query)
    dates = [entry['created_at'].strftime('%Y-%m-%d') for entry in daily_order_counts]
    counts = [entry['order_count'] for entry in daily_order_counts]
    print('Daily Chart Data:')
    print('Dates:', [entry['created_at'] for entry in daily_order_counts])
    print('Counts:', [entry['order_count'] for entry in daily_order_counts])
    print(dates)
    print(counts)


    end_date = timezone.now()
    start_date = end_date - timedelta(days=365) 
    
    monthly_order_counts = (
        CartOrder.objects
        .filter(created_at__range=(start_date, end_date))   
        .annotate(month=TruncMonth('created_at'))
        .values('month')
        .annotate(order_count=Count('id'))
        .order_by('month')
    )
    monthlyDates = [entry['month'].strftime('%Y-%m') for entry in monthly_order_counts]
    monthlyCounts = [entry['order_count'] for entry in monthly_order_counts]
    
    yearly_order_counts = (
        CartOrder.objects
        .annotate(year=TruncYear('created_at'))
        .values('year')
        .annotate(order_count=Count('id'))
        .order_by('year')
    )
    yearlyDates = [entry['year'].strftime('%Y') for entry in yearly_order_counts]
    yearlyCounts = [entry['order_count'] for entry in yearly_order_counts]

    statuses = ['Delivered','Paid','Pending', 'New', 'Conformed', 'Cancelled', 'Return','Shipped']
    order_counts = [CartOrder.objects.filter(status=status).count() for status in statuses]

    context={
        'service_count':service_count,
        'category_count':category_count,
        'orders_count':orders_count,
        'dates': dates,
        'counts': counts,
        'monthlyDates':monthlyDates,
        'monthlyCounts':monthlyCounts,
        'yearlyDates':yearlyDates,
        'yearlyCounts':yearlyCounts,
        'last_orders': last_orders,
        'revenue':revenue,
        'total_users_count': total_users_count,
        'statuses': statuses,
        'order_counts': order_counts,
    }
    return render(request, 'admin_side/admin_index.html', context)


@login_required(login_url='admin_login')
def admin_service(request):
    item = Service.objects.filter(is_deleted=False)
    context = {
        "item":item
    }
    return render(request,'admin_side/service.html',context)


@login_required(login_url='admin_login')
def admin_service_add(request):
    if request.method == 'POST':
        form = ServiceForm(request.POST,request.FILES)
        if form.is_valid():
            service=form.save(commit=False)
            service.save()
            images=request.FILES.getlist('images')
            for img in images:
                ServiceImages.objects.create(service=service,images=img)
            return redirect('admin_service')
    else:
        form = ServiceForm()    

    types = Type.objects.all()
    categories = category.objects.all()

    context = {
        'types': types,
        'categories': categories,
        'form' : form,
    }
    return render(request,'admin_side/service_add.html',context)


@login_required(login_url='admin_login')
def admin_service_edit(request, id):
    service = get_object_or_404(Service, id=id)
    types = Type.objects.all()
    categories = category.objects.all()

    ImageFormSet = inlineformset_factory(Service, ServiceImages, form=ServiceImagesForm, extra=1, can_delete=True)

    if request.method == 'POST':
        service_form = ServiceForm(request.POST, instance=service)
        formset = ImageFormSet(request.POST, request.FILES, instance=service)

        if service_form.is_valid() and formset.is_valid():
            service_form.save()
            formset.save()

            for form in formset.deleted_forms:
                instance = form.instance
                if instance.id:
                    instance.delete()

            return redirect('admin_service')

    else:
        service_form = ServiceForm(instance=service)
        formset = ImageFormSet(instance=service)

    context = {
        'service': service,
        'types': types,
        'categories': categories,
        'service_form': service_form,
        'formset': formset,
    }

    return render(request, 'admin_side/service_edit.html', context)

def admin_service_delete(request, id):
    service = get_object_or_404(Service, id=id)

    if request.method == 'POST':
        service.delete()
        return redirect('admin_service')

    context = {'service': service}
    return render(request, 'admin_side/service_delete.html', context)


@login_required(login_url='admin_login')
def customers(request):
    user = CustomUser.objects.all()
    context = {
        'user':user
    }
    return render(request, 'admin_side/customers.html',context)


@login_required(login_url='admin_login')
def block_user(request, user_id):
    user = get_object_or_404(CustomUser, id=user_id)

    if not user.is_admin:
        user.is_active = not user.is_active
        user.save()

        messages.success(request, f'{user.username} has been {"blocked" if not user.is_active else "unblocked"}.')
    else:
        messages.warning(request, 'You cannot block/unblock the Superadmin.')

    return redirect('customers')


@login_required(login_url='admin_login')
def admin_category(request):
    data=category.objects.filter(is_deleted=False)
    context={
        'data':data
    }
    return render(request, 'admin_side/category.html', context)


@login_required(login_url='admin_login')
def admin_category_insert(request):
    if request.method == 'POST':
        category_name = request.POST.get('name')

        try:
            new_cat = category(category_name=category_name)
            new_cat.save()
            return redirect('admin_category')

        except IntegrityError as e:
            messages.error(request, f"Category '{category_name}' already exists.")
            return redirect('admin_category')

    return render(request, 'admin_side/category.html')


@login_required(login_url='admin_login')
def admin_category_edit(request,id):
    if request.method == 'POST':
        category_name = request.POST.get('name')
        edit=category.objects.get(id=id)
        edit.category_name = category_name
        edit.save()
        return redirect('admin_category')
    obj = category.objects.get(id=id)
    context = {
        "obj":obj
    }
    return render(request,'admin_side/category_edit.html', context)

@login_required(login_url='admin_login')
def admin_delete_category(request, id):
    category_to_delete = get_object_or_404(category, id=id)
    category_to_delete.is_deleted = True
    category_to_delete.save()
    return redirect('admin_category')

@login_required(login_url='admin_login')
def block_unblock_category(request, id):
    category_to_block = get_object_or_404(category, id=id)
    category_to_block.is_blocked = not category_to_block.is_blocked
    category_to_block.save()
    return redirect('admin_category')


@login_required(login_url='admin_login')
def admin_type(request):

my_project/templates/admin_side/banner_create.html
{% extends 'admin_side/base.html' %}
{% load static %}
{% block content %}

<section class="content-main">
    <div class="row">
        <div class="col-9">
            <div class="content-header">
                <h2 class="content-title">Create Banner</h2>
                <div>
                    
                   
                </div>
            </div>
        </div>
        <div class="col-lg-12">
            <div class="card mb-4">
                <div class="card-header">
                    <h4>Banner</h4>
                </div>

                <div class="">
                  {% if messages %}
                  {% for message in messages %}
                  {{message}}
                  {% endfor %}
                  {% endif %}
                </div>


                <!-- {{form.errors}} -->
                <div class="card-body">
                  <form method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    <div class="row">
                        <div class="col-lg-6">
                            <div class="mb-4">
                                <label for="title" class="form-label">Title</label>
                                {{ form.title }}
                            </div>
                        </div>
                        <div class="col-lg-6">
                            <div class="mb-4">
                                <label for="image" class="form-label">Image</label>
                                {{ form.image }}
                            </div>
                        </div>
                        <div class="col-lg-6">
                            <div class="mb-4">
                                <label for="description1" class="form-label">Description1</label>
                                {{ form.description1 }}
                            </div>
                        </div>
                        <div class="col-lg-6">
                            <div class="mb-4">
                                <label for="description2" class="form-label">Description2</label>
                                {{ form.description2 }}
                            </div>
                        </div>
                        <div class="col-lg-6">
                            <div class="mb-4">
                                <label for="description3" class="form-label">Description3</label>
                                {{ form.description3 }}
                            </div>
                        </div>
                    </div>
                    <div class="row">
                      <div class="col-lg-6">
                        <div class="mb-4">
                            <label for="is_active" class="form-label">Status</label>
                            <input type="checkbox" name="is_active" id="is_active" {% if banner.is_active %}checked{% endif %}>
                        </div>
                    </div>
                        <div class="col-lg-6">
                            <div class="mb-4">
                                <label for="start_date" class="form-label">Active Date</label>
                                <input type="date" name="start_date" id="start_date" class="form-control" required>
                            </div>
                        </div>
                    </div>
                    <div class="mb-4">
                        <label for="end_date" class="form-label">Expiry Date</label>
                        <input type="date" name="end_date" id="id_expiry_date" class="end_date" required>
                    </div>
                
                    <!-- multi images -->
                    <div class="row">
                        <div class="col-lg-2">
                            <div class="mb-4">
                                <button type="submit" class="btn btn-primary btn-sm rounded col-lg-12">Create</button>
                            </div>
                        </div>
                    </div>
                </form>
                
                
                
                    
    </div>
    
       
</section>  

{% endblock %}      

my_project/templates/admin_side/base.html
{% load static %}
<!DOCTYPE HTML>
<html lang="en">


<!-- Mirrored from wp.alithemes.com/html/evara/evara-backend/index.html by HTTrack Website Copier/3.x [XR&CO'2014], Sun, 01 Aug 2021 15:32:35 GMT -->
<head>
    <meta charset="utf-8">
    <title>CRONICO</title>
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta property="og:title" content="">
    <meta property="og:type" content="">
    <meta property="og:url" content="">
    <meta property="og:image" content="">
    <!-- Favicon -->
    <link rel="shortcut icon" type="image/x-icon" href="{% static 'assets1/imgs/theme/favicon.svg' %}">
    <!-- Template CSS -->
    <link href="{% static 'assets1/css/main.css' %}" rel="stylesheet" type="text/css" />
</head>
<body>
{% include "admin_side/includes/nav.html" %}
{% block content %}

{% endblock %}
{% include "admin_side/includes/footer.html"%}


</body></html>

my_project/templates/admin_side/create-service-offers.html
{% extends 'admin_side/base.html' %}
{% load static %}
{% comment %} {% block title %} Service Details {% endblock %}
{% block  body %} {% endcomment %}
{% block content %}

<section class="content-main">
    <div class="row">
        <div class="col-9">
            <div class="content-header">
                <h2 class="content-title">Create Service Offer</h2>
                <div>
                    
                   
                </div>
            </div>
        </div>
        <div class="col-lg-12">
            <div class="card mb-4">
                <div class="card-header">
                    <h4>Service Details</h4>
                </div>

                <div id="createoffer">
                  {% if messages %}
                  {% for message in messages %}
                  {{message}}
                  {% endfor %}
                  {% endif %}
                </div>
                <div class="alert alert-danger " id="alertoffer">
                  {{form.errors}}
                </div>
                <script>
                  // Add a script to hide the alert after 3 seconds
                  setTimeout(function() {
                    var alert = document.getElementById('createoffer');
                    if (alert) {
                      alert.style.display = 'none';
                    }
                  }, 3000);  // 3000 milliseconds = 3 seconds

                  setTimeout(function() {
                    var alert = document.getElementById('alertoffer');
                    if (alert) {
                      alert.style.display = 'none';
                    }
                  }, 3000);  // 3000 milliseconds = 3 seconds
                </script>


                <!-- {{form.errors}} -->
                <div class="card-body">
                  <form method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    <div class="row">
                        <div class="col-lg-6">
                            <div class="mb-4">
                                <label for="id_code" class="form-label">Discount</label>
                                {{form.discount_percentage}}
                            </div>
                        </div>
                        
                    </div>
                    <div class="row">
                      <div class="col-lg-6">
                        <!-- <div class="mb-4">
                            <label for="id_active" class="form-label">Status</label>
                            <input type="checkbox" name="active" id="id_active" {% if form.active %}checked{% endif %}>
                        </div> -->
                        <div class="mb-4">
                          <label class="form-label">Status</label>
                          <button type="button" id="toggleStatusButton" onclick="toggleStatus()">
                              {% if not form.active %}Deactivate{% else %}Activate{% endif %}
                          </button>
                          <!-- <input type="hidden" name="active" id="id_active" value="{% if form.active %}True{% else %}False{% endif %}"> -->
                          <input type="hidden" name="active" id="id_active" value="False">
                      </div>
                    </div>
                        <div class="col-lg-6">
                            <div class="mb-4">
                                <label for="id_active_date" class="form-label">Active Date</label>
                                {{form.start_date}}
                            </div>
                        </div>
                    </div>
                    <div class="mb-4">
                        <label for="id_expiry_date" class="form-label">Expiry Date</label>
                        {{form.end_date}}
                    </div>
                
                    <!-- multi images -->
                    <div class="row">
                        <div class="col-lg-2">
                            <div class="mb-4">
                                <button type="submit" class="btn btn-primary btn-sm rounded col-lg-12">Create</button>
                            </div>
                        </div>
                    </div>
                </form>
                
                
                
                    
    </div>
    
       
</section>  

<script>
  function toggleStatus() {
      const activeInput = document.getElementById('id_active');
      const toggleStatusButton = document.getElementById('toggleStatusButton');
      
      activeInput.value = (activeInput.value === 'True') ? 'False' : 'True';
      toggleStatusButton.textContent = (activeInput.value === 'True') ? 'Deactivate' : 'Activate';
  }
</script>

{% endblock %}      

my_project/templates/admin_side/create_coupon.html
{% extends 'admin_side/base.html' %}
{% load static %}
{% block  content %}

<section class="content-main">
    <div class="row">
        <div class="col-9">
            <div class="content-header">
                <h2 class="content-title">Add Coupon</h2>
                <div>
                    
                   
                </div>
            </div>
        </div>
        <div class="col-lg-12">
            <div class="card mb-4">
                <div class="card-header">
                    <h4>Coupon Details</h4>
                </div>

                <div class="">
                  {% if messages %}
                  {% for message in messages %}
                  {{message}}
                  {% endfor %}
                  {% endif %}
                </div>


                <!-- {{form.errors}} -->
                <div class="card-body">
                  <form method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    <div class="row">
                        <div class="col-lg-6">
                            <div class="mb-4">
                                <label for="id_code" class="form-label">Coupon name</label>
                                <input type="text" name="code" id="id_code" class="form-control" required>
                            </div>
                        </div>
                        <div class="col-lg-6">
                            <div class="mb-4">
                                <label for="id_discount" class="form-label">Discount</label>
                                <input type="number" name="discount" id="id_discount" class="form-control" required>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                      <div class="col-lg-6">
                        <div class="mb-4">
                            <label for="id_active" class="form-label">Status</label>
                            <input type="checkbox" name="active" id="id_active" {% if coupon.active %}checked{% endif %}>
                        </div>
                    </div>
                        <div class="col-lg-6">
                            <div class="mb-4">
                                <label for="id_active_date" class="form-label">Active Date</label>
                                <input type="date" name="active_date" id="id_active_date" class="form-control" required>
                            </div>
                        </div>
                    </div>
                    <div class="mb-4">
                        <label for="id_expiry_date" class="form-label">Expiry Date</label>
                        <input type="date" name="expiry_date" id="id_expiry_date" class="form-control" required>
                    </div>
                
                    <!-- multi images -->
                    <div class="row">
                        <div class="col-lg-2">
                            <div class="mb-4">
                                <button type="submit" class="btn btn-primary btn-sm rounded col-lg-12">Create</button>
                            </div>
                        </div>
                    </div>
                </form>
                
                
                
                    
    </div>
    
       
</section>  

{% endblock %}      