my_project/my_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("user_side.urls")),
    path("", include("admin_side.urls")),
    path('payment/',include('payment.urls')),
    
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

my_project/payment/urls.py
from django.urls import path
from .import views

urlpatterns = [
    path('',views.checkout,name='checkout'),
    path('payment/',views.payment,name="payment"),
    path('paymenthandler/', views.paymenthandler, name='paymenthandler'),
    path('online_place_order', views.online_place_order, name='online_place_order'),
    path('place_order/',views.place_order,name="place_order"),
    path('order_success/', views.order_success, name='order_success'),
    path('wallet_place_order', views.wallet_place_order, name='wallet_place_order'),
    path('invoice/<int:order_id>/',views.invoice,name='invoice'),


]

my_project/user_side/urls.py
from django.urls import path
from user_side import views


urlpatterns = [
    path('user_login/',views.signin,name='user_login'),
    path('user_logout/',views.user_logout,name='user_logout'),
    path("", views.index, name="index"),
    path('user_login/', views.user_login, name='user_login'),
    path('user_signup/', views.user_signup, name='user_signup'),
    path('enter_otp/',views.enter_otp,name='enter_otp'),
    path('resend_otp/',views.resend_otp,name='resend_otp'),
    path('services/', views.services, name='services'),
    path('service/<int:category_id>/<int:service_id>', views.service_details, name='service_details'),
    path('search/',views.search,name='search'),
    path('add_to_cart/',views.add_to_cart, name='add_to_cart'),
    path('cart/', views.cart_list, name='cart'),
    path('update_qty',views.qty_update,name='update_qty'),
    path('delete_cart_item/', views.delete_cart_item, name='delete_cart_item'),
    path('user_account/', views.user_account, name='user_account'),
    path('add_address/', views.add_address, name='add_address'),
    path('edit-address/<int:address_id>/', views.edit_address, name='edit_address'),
    path('delete-address/<int:address_id>/', views.delete_address, name='delete_address'),
    path('order_items/<int:order_number>/', views.order_items, name='order_items'),
    path('cancell/<int:order_number>/',views.cancell,name='cancell'),
    path('change_password/', views.change_password, name='change_password'),
    path('add_wishlist/<int:service_id>/',views.add_wishlist,name='add_wishlist'),
    path('wishlist',views.wishlist,name='wishlist'),
    path('delete_wishlist/<int:wishlist_item_id>/',views.delete_wishlist,name='delete_wishlist'),
    path('filter-service/', views.filter_service,name='filter-service'),
















]

my_project/user_side/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser,BaseUserManager,PermissionsMixin,Group,Permission
from django.core.validators import FileExtensionValidator
from django.utils.safestring import mark_safe
from django.utils import timezone

# Create your models here.

class CustomUserManager(BaseUserManager):
    def create_user(self,first_name,last_name,username,email,password=None):
        if not email:
            raise ValueError('User must an email address')
        if not username:
            raise ValueError('User must have a username')
        
        user = self.model(
            email = self.normalize_email(email),
            username = username,
            first_name = first_name,
            last_name = last_name
        )
        user.set_password(password)
        user.save(using = self._db)
        return user
    
    def create_superuser(self,first_name,last_name,username,email,password=None):
        user = self.create_user(
            email = self.normalize_email(email),
            username = username,
            password = password,
            first_name = first_name,
            last_name = last_name
        )
        user.is_admin = True
        user.is_active = True
        user.is_staff = True
        user.is_superadmin = True
        user.save(using=self._db)
        return user

class CustomUser(AbstractBaseUser,PermissionsMixin):
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    username = models.CharField(max_length=100,unique=True)
    email = models.EmailField(max_length=200,unique=True)
    phone = models.CharField(max_length=12,blank=True)

    #required fiels
    date_joined = models.DateTimeField(auto_now_add=True)
    last_login = models.DateTimeField(auto_now_add=True)
    created_date = models.DateTimeField(auto_now_add=True)
    modified_date = models.DateTimeField(auto_now=True)
    is_admin = models.BooleanField(default=False)
    is_staff = models.BooleanField(default=False)
    is_active = models.BooleanField(default=True)
    is_superadmin = models.BooleanField(default=False)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['username','first_name','last_name']
    objects=CustomUserManager()

    groups=models.ManyToManyField(Group,blank=True,related_name='home_user_groups')
    user_permissions=models.ManyToManyField(Permission,blank=True,related_name='home_user_permissions')
    def __str__(self):
        return self.email
    def has_perm(self, perm, obj=None):
        return self.is_admin
    def has_module_perms(self,app_lebel):
        return True
    
class category(models.Model):
    category_name=models.CharField(max_length=100,unique=True)
    is_blocked = models.BooleanField(default=False)
    is_deleted = models.BooleanField(default=False)

    def __str__(self) :
        return self.category_name
    
class Type(models.Model):
    type_name = models.CharField(max_length=255,unique=True)
    is_active = models.BooleanField(default=True)

    def __str__(self) :
        return self.type_name
    
class ProviderType(models.Model):
    provider_type_name = models.CharField(max_length=100)
    provider_type_code = models.CharField(max_length=100)

    def provider_type_bg(self):
        return mark_safe('<div style="width:50px; height:50px; background-provider_type=%s"></div>' % (self.provider_type_code))

    def __str__(self):
        return self.provider_type_name


class Service(models.Model):
    service_name = models.CharField(max_length=255)
    description = models.TextField(null=True)
    is_available=models.BooleanField(default=True)
    type = models.ForeignKey('Type', on_delete=models.CASCADE, default=1)
    category = models.ForeignKey('category', on_delete=models.CASCADE)
    featured = models.BooleanField(default=False)
    specifications = models.TextField(null =True, blank =True)
    is_deleted = models.BooleanField(default=False)

    class Meta:
        verbose_name_plural = "Services"

    def soft_delete(self):
        self.is_deleted = True
        self.save()

    def undo(self):
        self.is_deleted = False
        self.save()

    def __str__(self):
        return self.service_name
    
    def get_percentage(self):
        new_price = (self.price /self.old_price) * 100
        return new_price

class ServiceImages(models.Model):
    service = models.ForeignKey(Service ,related_name='service_image',on_delete=models.SET_NULL, null = True)
    images = models.ImageField(upload_to='photo/service_images3',
        validators=[
            FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'], message="Only JPG, JPEG, and PNG files are allowed.")
                    ])
    date = models.DateTimeField(auto_now_add= True)
    
    class Meta:
        verbose_name_plural = "Service Images"

class ServiceAttribute(models.Model):
    service = models.ForeignKey(Service, on_delete=models.CASCADE)
    provider_type = models.ForeignKey(ProviderType, on_delete=models.CASCADE, default=1)
    price = models.PositiveIntegerField()
    availability = models.IntegerField(default=0)
    old_price = models.PositiveIntegerField(default=0)
    is_available=models.BooleanField(default=True)
    is_deleted = models.BooleanField(default=False)
    image = models.ImageField(upload_to='photo/service_images',
        validators=[
            FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'], message="Only JPG, JPEG, and PNG files are allowed.")
                    ],
                    default=timezone.now  # Example default value using timezone.now
                    )
    def __str__(self):
        return f"{self.service} - {self.provider_type} - ${self.price}"
    def image_tag(self):
        return mark_safe('<img src="%s" width="50" height="50" />' % self.image.url)
    

class WishlistItem(models.Model):
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    service = models.ForeignKey(Service, on_delete=models.CASCADE)

my_project/user_side/forms.py
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from django import forms
from .models import *
from django.core.exceptions import ValidationError
from django.forms import modelformset_factory

class SignUpForm(UserCreationForm):
    class Meta:
        model= CustomUser
        fields=['username','first_name','last_name','email','phone','password']

class AddToCartForm(forms.Form):
    quantity = forms.IntegerField(min_value=1, initial=1)
    
class CategoryForm(forms.ModelForm):
    class Meta:
        model = category
        fields=['category_name']
class TypeFrom(forms.ModelForm):
    class Meta:
        model=Type
        fields=['type_name']
class ProviderTypeForm(forms.ModelForm):
    class Meta:
        model=ProviderType
        fields=['provider_type_name','provider_type_code']
class ServiceForm(forms.ModelForm):
    def __init__(self,*args, **kwargs):
        super().__init__(*args, **kwargs)
        # for i, fields in self.fields.items():
        #     fields.widget.attrs['class'] = 'form-control'
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'
            # Check if the field is a BooleanField and customize its rendering
            if isinstance(field, forms.BooleanField):
                field.widget = forms.CheckboxInput(attrs={'class': 'form-check-input'})
    class Meta:
        model=Service
        fields=['service_name','description','is_available','specifications','type','category','featured','is_deleted']
   
class ServiceImagesForm(forms.ModelForm):

    delete_image = forms.BooleanField(required=False, initial=False,widget=forms.HiddenInput)

    class Meta:
        model = ServiceImages
        fields = ['images']

    def __init__(self, *args, **kwargs):
        super(ServiceImagesForm, self).__init__(*args, **kwargs)
        self.fields['images'].required = False




class ServiceAttributeForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'
            if isinstance(field, forms.BooleanField):
                field.widget = forms.CheckboxInput(attrs={'class': 'form-check-input'})

    class Meta:
        model = ServiceAttribute
        fields = ['service', 'provider_type', 'price','old_price', 'availability', 'image', 'is_deleted', 'is_available']

    def clean_image(self):
        image = self.cleaned_data.get('image')
        if image:
            try:
                # Attempt to validate the image extension
                image_extension = image.name.split('.')[-1].lower()
                valid_extensions = ['jpg', 'jpeg', 'png']
                if image_extension not in valid_extensions:
                    raise ValidationError("Only JPG, JPEG, and PNG files are allowed.")
            except AttributeError:
                # Handle the case where 'image' does not have a 'name' attribute
                raise ValidationError("Invalid image file.")
        return image
    def clean_price(self):
        price = self.cleaned_data.get('price')
        if price < 0:
            raise forms.ValidationError('Price cannot be negative.')
        return price
    def clean_availability(self):
        availability = self.cleaned_data.get('availability')
        if availability < 0:
            raise forms.ValidationError('Availability cannot be negative.')
        return availability
    

my_project/templates/user_side/add_address.html
{% extends 'user_side/base.html' %}

{% block content %}
<div class="container mt-4">
  <div class="row justify-content-center">
    <div class="col-md-8">
      <div class="card">
        <div class="card-header">
          <h2 class="mb-0">Edit Address</h2>
        </div>
        <div class="card-body">
          <form method="post" action="{% url 'add_address' %}">

            {% csrf_token %}
            
            <div class="row">
                <div class="col-lg-5">
                    {{ form.as_p }}
                    <!-- Repeat the pattern for other form fields -->
                </div>
                
                <div class="d-grid">
                    <button class="btn btn-primary">Add address</button>
                </div>
            </div>
            {% comment %} <div class="mb-3">
              <label for="{{ form.users.id_for_label }}" class="form-label">User</label>
              {{ form.users }}
            </div>
            <div class="mb-3">
              <label for="{{ form.name.id_for_label }}" class="form-label">Name</label>
              {{ form.name }}
            </div>
            <div class="mb-3">
              <label for="{{ form.address.id_for_label }}" class="form-label">Address</label>
              {{ form.address }}
            </div>
            <div class="mb-3">
              <label for="{{ form.district.id_for_label }}" class="form-label">District</label>
              {{ form.district }}
            </div>
            <div class="mb-3">
              <label for="{{ form.pincode.id_for_label }}" class="form-label">Pincode</label>
              {{ form.pincode }}
            </div>
            <div class="mb-3">
              <label for="{{ form.phone.id_for_label }}" class="form-label">Phone</label>
              {{ form.phone }}
            </div>
            <button type="submit" class="btn btn-primary">Save Changes</button> {% endcomment %}
          </form>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

my_project/templates/user_side/edit_address.html
{% extends 'user_side/base.html' %}

{% block content %}
<div class="container mt-4">
  <div class="row justify-content-center">
    <div class="col-md-8">
      <div class="card">
        <div class="card-header">
          <h2 class="mb-0">Edit Address</h2>
        </div>
        <div class="card-body">
          <form method="post" action="{% url 'edit_address' address.id %}">

            {% csrf_token %}
            {% comment %} <div class="mb-3">
              <label for="{{ form.users.id_for_label }}" class="form-label">User</label>
              {{ form.users }}
            </div> {% endcomment %}
            <div class="mb-3">
              <label for="{{ form.name.id_for_label }}" class="form-label">Name</label>
              {{ form.name }}
            </div>
            <div class="mb-3">
              <label for="{{ form.address.id_for_label }}" class="form-label">Address</label>
              {{ form.address }}
            </div>
            <div class="mb-3">
              <label for="{{ form.district.id_for_label }}" class="form-label">District</label>
              {{ form.district }}
            </div>
            <div class="mb-3">
              <label for="{{ form.pincode.id_for_label }}" class="form-label">Pincode</label>
              {{ form.pincode }}
            </div>
            <div class="mb-3">
              <label for="{{ form.phone.id_for_label }}" class="form-label">Phone</label>
              {{ form.phone }}
            </div>
            <button type="submit" class="btn btn-primary">Save Changes</button>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

my_project/templates/user_side/search.html
{% extends 'user_side/base.html'%}
{% load static %}
{% block content %}
    <!-- Quick view -->
    
                <!--End nav-tabs-->
                <section class="mt-50 mb-50">
                    <div class="container">
                
                <div class="tab-content wow fadeIn animated" id="myTabContent">
                    <div class="tab-pane fade show active" id="tab-one" role="tabpanel" aria-labelledby="tab-one">
                        <div class="row product-grid-4">
                            <h3>Search for result {{request.GET.q}}
                            </h3>
                            <br><br><br>
                            {% for service in data %}
                            <div class="col-lg-3 col-md-4 col-12 col-sm-6">
                                <div class="product-cart-wrap mb-30">
                                    <div class="product-img-action-wrap">
                                        <div class="product-img product-img-zoom">
                                            
                                            {% comment %} <a href="{% url 'product_details' product_name=product.product_name id=product.id %}"> {% endcomment %}
                                            <a href="{% url 'service_details' category_id=service.category.id service_id=service.id %}"> 
                                                <img class="default-img" src="{{ service.serviceattribute_set.first.image.url }}" alt="product image">
                                                {% comment %} <img class="hover-img" src="{{ product.product_image1.url }}" alt=""> {% endcomment %}
                                            </a>
                                            {% if discount_offer is not None and discount_offer.active %}
                                    <div class="product-badges product-badges-position product-badges-mrg">
                                        <span class="hot">-{{ discount_offer.discount_percentage|floatformat:0 }}%</span>
                                    </div>
                                    {% elif discounted_offer %}
                                    {% for dis in discounted_offer %}
                                        {% if dis.active and dis.category == service.category %}
                                        <div class="product-badges product-badges-position product-badges-mrg">
                                            <span class="hot">-{{ dis.discount_percentage|floatformat:0 }}%</span>
                                        </div>
                                            {% else %}
                                            <div class="product-badges product-badges-position product-badges-mrg">
                                                <span class="hot">Best Deal</span>
                                            </div>
                                        {% endif %}
                                    {% endfor %}
                                {% else %}
                                    <div class="product-badges product-badges-position product-badges-mrg">
                                        <span class="hot">Best Deal</span>
                                    </div>
                                {% endif %}
                                        </div>
                                        <div class="product-action-1">
                                            <a aria-label="Add To Wishlist" class="action-btn hover-up" href="{% url 'add_wishlist' service.id%}">
                                                <i class="fi-rs-heart"></i>
                                            </a>
                                        </div>
                                        {% comment %} <div class="product-badges product-badges-position product-badges-mrg">
                                            <span class="hot">Hot</span>
                                        </div>{% endcomment %}
                                    </div>
                                    <div class="product-content-wrap">
                                        <div class="product-category">
                                            <a href="shop-grid-right.html">{{ service.category }}</a>
                                        </div>
                                        <h2><a href="">{{ service.service_name }}</a></h2>
                                        <div >
                                            {% comment %} <span>
                                                <span>90%</span>
                                            </span> {% endcomment %}
                                        </div>
                                        {% if discount_offer is not None and discount_offer.active %}
                                                <div class="product-price">
                                                    <span class="current-product-price-{{service.id}}">₹{{service.serviceattribute_set.first.price}}</span>
                                                    <span class="old-price">₹{{service.serviceattribute_set.first.old_price}}</span>
                                                </div>
                                            {% elif discounted_offer %}
                                                {% for dis in discounted_offer %}
                                                    {% if dis.active and dis.category == service.category %}
                                                        <div class="product-price">
                                                            <span>₹ <span class="current-product-price-{{service.id}}">{{service.serviceattribute_set.first.price}}</span></span>
                                                            <br>₹<span class="old-price">{{service.serviceattribute_set.first.old_price}}</span>
                                                        </div>
                                                        {% else %}
                                                        <div class="product-price">
                                                            <span>₹ <span class="current-product-price-{{service.id}}">{{service.serviceattribute_set.first.price}}</span></span>
                                                            
                                                        </div>
                                                    {% endif %}
                                                {% endfor %}
                                            {% else %}
                                                <div>
                                                    <span style="font-size: large;">
                                                        ₹<span class="current-product-price-{{service.id}} text-success" style="font-weight: bold;">{{service.serviceattribute_set.first.price}}</span>
                                                    </span>
                                                </div>
                                            {% endif %}
                                        {% comment %} <div class="product-action-1 show">
                                            <a aria-label="Add To Cart" class="action-btn hover-up" href="shop-cart.html"><i class="fi-rs-shopping-bag-add"></i></a>
                                        </div> {% endcomment %}
                                    </div>
                                </div>
                            </div>
                            {% endfor %}
                            
                            
                        </div>
                        <!--End product-grid-4-->
                    </div>
                    <!--En tab one (Featured)-->
                    
        <section class="deals section-padding">
            <div class="container">
                <div class="row">
                    <div class="col-lg-6 deal-co">
                        <div class="deal wow fadeIn animated mb-md-4 mb-sm-4 mb-lg-0" style="background-image: url('{% static 'assets/imgs/banner/banner200.jpg'%}');">
                             <div class="deal-top">
                                <h2 class="text-brand"></h2>
                                
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-6 deal-co">
                        <div class="deal wow fadeIn animated" style="background-image: url('{% static 'assets/imgs/banner/banner400.jpg'%}');">
                        </div>
                    </div>
                </div>
            </div>
        </section>
       
       
        <section class="mb-50">
            <div class="container">
                <div class="row">
                    <div class="col-12">
                        <div class="banner-bg wow fadeIn animated" style="background-image: url('{% static 'assets/imgs/banner/banner-80.jpg'%}')">
                            <div class="banner-content">
                                <h4 class="text-grey-4 mb-15">ABOUT Xpertise</h4>
                                <h6class="fw-600">Welcome to Xpertise, your premier destination for doorstep services! At Xpertise, we're more than just a service provider; we're your trusted partner in simplifying your life and enhancing your experience. From home maintenance to beauty treatments and professional consultations, our mission is to deliver expert solutions directly to your doorstep, ensuring unparalleled convenience and quality.</h6>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section> 
        
    </main>
{% endblock %}

my_project/templates/user_side/service_list.html
<div class="row product-grid-3">
    {% for service in services %}
    <div class="col-lg-3 col-md-4">
        <div class="product-cart-wrap mb-30">
            <div class="product-img-action-wrap">
                <div class="product-img product-img-zoom " style="height: 300px; overflow: hidden;">
                   
                    <a href="{% url 'service_details' category_id=service.category.id service_id=service.id %}"> 
                        
   
                        {% if service.serviceattribute_set.first.image %}
                            <img class="default-img" src="{{ service.serviceattribute_set.first.image.url }}" alt="" style="width: 100%; height: auto;">
                        {% else %}
                            <!-- Handle the case where the image is missing or not set -->
                            <p>No Image Available</p>
                        {% endif %}
                    </a>
                    
                       
                </div>
                <div class="product-action-1">
                    
                   
                    <a aria-label="Add To Wishlist" class="action-btn hover-up" href="{% url 'add_wishlist' service.id%}">
                        <i class="fi-rs-heart"></i>
                    </a>
                    
                </div>
                {% if discount_offer is not None and discount_offer.active %}
                  <div class="product-badges product-badges-position product-badges-mrg">
                      <span class="hot">-{{ discount_offer.discount_percentage|floatformat:0 }}%</span>
                  </div>
                  {% elif discounted_offer %}
                  {% for dis in discounted_offer %}
                      {% if dis.active and dis.category == service.category %}
                      <div class="product-badges product-badges-position product-badges-mrg">
                          <span class="hot">-{{ dis.discount_percentage|floatformat:0 }}%</span>
                      </div>
                          {% else %}
                          <div class="product-badges product-badges-position product-badges-mrg">
                              <span class="hot">Hot</span>
                          </div>
                      {% endif %}
                  {% endfor %}
              {% else %}
                  <div class="product-badges product-badges-position product-badges-mrg">
                      <span class="hot">Hot</span>
                  </div>
              {% endif %}
               
            </div>
            <div class="product-content-wrap">
                <div class="product-category">
                    <a href="shop-grid-right.html">{{ service.category }}</a>
                </div>
                
  
                <h2><a href="#">{{ service.service_name }}</a></h2>
                {% comment %} <div class="rating-result" title="90%">
                    <span>
                        <span>90%</span>
                    </span>
                </div> {% endcomment %}
                {% if discount_offer is not None and discount_offer.active %}
                <div class="product-price">
                    <span class="current-product-price-{{service.id}}">₹{{service.serviceattribute_set.first.price}}</span>
                    <span class="old-price">₹{{service.serviceattribute_set.first.old_price}}</span>
                </div>
            {% elif discounted_offer %}
                {% for dis in discounted_offer %}
                    {% if dis.active and dis.category == service.category %}
                        <div class="product-price">
                            <span>₹ <span class="current-product-price-{{service.id}}">{{service.serviceattribute_set.first.price}}</span></span>
                            ₹<span class="old-price">{{service.serviceattribute_set.first.old_price}}</span>
                        </div>
                        {% else %}
                        <div class="product-price">
                            <span>₹ <span class="current-product-price-{{service.id}}">{{service.serviceattribute_set.first.price}}</span></span>
                            
                        </div>
                    {% endif %}
                {% endfor %}
            {% else %}
                <div>
                    <span style="font-size: large;">
                        ₹<span class="current-product-price-{{service.id}} text-success" style="font-weight: bold;">{{service.serviceattribute_set.first.price}}</span>
                    </span>
                </div>
            {% endif %}
  
            </div>
        </div>
    </div>
    {% endfor %}
  </div>